import org.gradle.api.JavaVersion

object Config{
    const val compileSdkVersion = 30
    const val buildToolsVersion = "30.0.2"
    const val applicationId="com.github.kongpf8848.updatedialog"
    const val minSdkVersion = 21
    const val targetSdkVersion = 30
    val sourceCompatibilityVersion = JavaVersion.VERSION_1_8
    val targetCompatibilityVersion = JavaVersion.VERSION_1_8
    const val versionCode = 1
    const val versionName = "1.0"

}

object Versions {

    const val PLUGIN_GRADLE_VERSION="3.6.3"
    const val PLUGIN_GMS_VERSION="3.1.1"
    const val KOTLIN_VERSION = "1.3.60"
    //google-services
    const val GOOGLE_SERVICE = "4.3.4"
    const val FIREBASE_BOM = "26.2.0"

    const val ANDROIDX_APP_COMPAT_VERSION = "1.2.0"
    const val ANDROIDX_LEGACY_V4_VERSION = "1.0.0"
    const val ANDROIDX_LEGACY_V13_VERSION = "1.0.0"
    const val ANDROIDX_MULTIDEX_VERSION = "2.0.1"
    const val ANDROIDX_MATERIAL_VERSION = "1.0.0"
    const val ANDROIDX_RECYCLERVIEW_VERSION = "1.1.0"
    const val ANDROIDX_PREFERENCE_VERSION = "1.1.1"
    const val ANDROIDX_CARDVIEW_VERSION = "1.0.0"
    const val ANDROIDX_GRIDLAYOUT_VERSION = "1.0.0"
    const val ANDROIDX_ANNOTATION_VERSION = "1.1.0"
    const val ANDROIDX_CONSTRAINTLAYOUT_VERSION = "2.0.4"
    const val ANDROIDX_PAGING_VERSION = "2.1.2"
    const val ANDROIDX_WORK_RUNTIME_VERSION = "2.4.0"
    const val ANDROIDX_CORE_VERSION="1.3.2"
    const val ANDROIDX_CORE_KTX_VERSION="1.3.2"
    const val ANDROIDX_ROOM_VERSION="2.2.5"
    const val ANDROIDX_COORDINATORLAYOUT_VERSION="1.1.0"
    const val ANDROIDX_DATABINDING_VERSION="4.1.0"
    const val ANDROIDX_ACTIVITY_VERSION="1.2.0-alpha06"
    const val ANDROIDX_FRAGMENT_VERSION="1.3.0-alpha06"
    const val ANDROIDX_LIFECYCLE_VERSION="2.2.0"
    const val ANDROIDX_LIFECYCLE_ARCH_VERSION="2.1.0"
    const val ANDROIDX_VIEWPAGER_VERSION="1.1.0"

    const val GOOGLE_PLAY_SERVICES_VERSION = "17.0.0"
    const val GOOGLE_FIREBASE_MESSAGING_VERSION = "17.3.0"

    const val GSON_VERSION = "2.8.2"
    const val JUNIT_VERSION = "4.12"
    const val LEAKCANARY_VERSION = "1.6.3"
    const val IMMERSIONBAR_VERSION = "3.0.0"
    const val IJKPLAYER_VERSION = "0.8.8"
    const val HMS_PUSH_VERSION="3.0.2.300"
    const val FLYME_PUSH_VERSION="3.8.4"

    const val SUPPORT_PREFERENCE_VERSION = "0.8.1"
    const val EVERNOTE_ANDROIDJOB_VERSION = "1.2.6"
    const val FACEBOOK_REBOUND_VERSION = "0.3.8"
    const val ATLASSIAN_COMMONMARK_VERSION = "0.11.0"
    const val JAVADEV_JNAAAR_VERSION = "4.4.0@aar"
    const val RXJAVA2_VERSION = "2.1.9"
    const val RXANDROID_VERSION = "2.0.2"
    const val RETROFIT_VERSION = "2.9.0"
    const val OKHTTP_VERSION = "4.9.0"
    const val ZXING_CORE_VERSION = "3.4.1"
    const val ZXING_ANDROID_CORE_VERSION = "3.4.1"
    const val ZXING_BARCODE_SCANNER_VERSION = "1.9"
    const val ORMLITE_VERSION = "5.1"
    const val BASEQUICKADAPTER_VERSION = "3.0.6"
    const val GLIDE_VERSION = "4.9.0"
    const val PRETTYTIME_VERSION = "4.0.1.Final"
    const val SWIPEDELMENULAYOUT_VERSION = "V1.3.0"
    const val PHOTOVIEW_VERSION = "2.1.3"
    const val PERCENT_VERSION = "1.1.1"
    const val APPCENTER_VERSION = "4.0.0"
    const val STETHO_VERSION = "1.5.0"
    const val TIMMER_VERSION = "4.7.0"
    const val THREETENABP_VERSION = "1.1.1"
    const val YANZHENJIE_RECYCLERVIEW_VERSION = "1.3.2"
    const val SMARTREFRESHLAYOUT_VERSION = "1.1.0"
    const val GIF_DRAWABLE_VERSION = "1.2.19"
    const val LUBAN_VERSION = "1.1.8"
    const val NANOHTTPD_VERSION = "2.2.0"
    const val SHORTCUTBADGER_VERSION = "1.1.22"
    const val ANDROIDSVG_VERSION = "1.2.1"
    const val STICKYHEADERS_VERSION = "0.4.3@aar"
    const val ANIMATED_WEBP_VERSION = "1.9.0"
    const val JSOUP_VERSION = "1.12.1"
    const val RXHTTP_VERSION="1.0.7"
    const val TYPE_BUILDER_VERSION="1.0"
    const val AUTODISPOSE_VERSION="1.4.0"
    const val RXLIFECYCLE_VERSION="2.0.1"
    const val BUTTER_KNIFE_VERSION = "10.2.3"
    const val BGA_BANNER_VERSION="2.1.8"
    const val GOOGLE_PHONENUMBER_VERSION = "8.10.7"
    const val EVENT_BUS_VERSION = "3.2.0"
    const val KOTLINX_COROUTINES_ANDROID_VERSION = "1.3.9"
    const val ANDROID_IMAGE_CROPPER_VERSION = "2.8.0"
    const val GSY_VIDEOPLAYER_VERSION = "8.0.0"
    const val COMMON_HELPER_VERSION="1.0.21"
    const val ROUND_CORNERS_VERSION="1.0.4"

}

object BuildDependencies {

    const val junit = "junit:junit:${Versions.JUNIT_VERSION}"
    const val immersionbar = "com.gyf.immersionbar:immersionbar:${Versions.IMMERSIONBAR_VERSION}"
    const val immersionbarComponents = "com.gyf.immersionbar:immersionbar-components:${Versions.IMMERSIONBAR_VERSION}"
    const val immersionbarKtx = "com.gyf.immersionbar:immersionbar-ktx:${Versions.IMMERSIONBAR_VERSION}"
    const val leakcanaryAndroid = "com.squareup.leakcanary:leakcanary-android:${Versions.LEAKCANARY_VERSION}"
    const val leakcanaryAndroidNoop = "com.squareup.leakcanary:leakcanary-android-no-op:${Versions.LEAKCANARY_VERSION}"
    const val leakcanarySupportFragment = "com.squareup.leakcanary:leakcanary-support-fragment:${Versions.LEAKCANARY_VERSION}"
    const val hmsPush = "com.huawei.hms:push:${Versions.HMS_PUSH_VERSION}"
    const val hmsOpenDevice = "com.huawei.hms:opendevice:${Versions.HMS_PUSH_VERSION}"
    const val flymePush = "com.meizu.flyme.internet:push-internal:${Versions.FLYME_PUSH_VERSION}"
    const val firbaseBom = "com.google.firebase:firebase-bom:${Versions.FIREBASE_BOM}"
    const val firbaseAnalyticsKtx = "com.google.firebase:firebase-analytics-ktx"
    const val firbaseMessagingKtx = "com.google.firebase:firebase-messaging-ktx"
    const val gson = "com.google.code.gson:gson:${Versions.GSON_VERSION}"
    const val kotlinStdlibJdk7 = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.KOTLIN_VERSION}"
    const val kotlinxCoroutinesAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.KOTLINX_COROUTINES_ANDROID_VERSION}"
    const val playServicesBase = "com.google.android.gms:play-services-base:${Versions.GOOGLE_PLAY_SERVICES_VERSION}"
    const val playServicesMaps = "com.google.android.gms:play-services-maps:${Versions.GOOGLE_PLAY_SERVICES_VERSION}"
    const val playServicesLocation = "com.google.android.gms:play-services-location:${Versions.GOOGLE_PLAY_SERVICES_VERSION}"
    const val playServicesGcm = "com.google.android.gms:play-services-gcm:${Versions.GOOGLE_PLAY_SERVICES_VERSION}"
    const val firebaseMessaging = "com.google.firebase:firebase-messaging:${Versions.GOOGLE_FIREBASE_MESSAGING_VERSION}"
    const val androidJob = "com.evernote:android-job:${Versions.EVERNOTE_ANDROIDJOB_VERSION}"
    const val rxjava2 = "io.reactivex.rxjava2:rxjava:${Versions.RXJAVA2_VERSION}"
    const val rxAndroid = "io.reactivex.rxjava2:rxandroid:${Versions.RXANDROID_VERSION}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.RETROFIT_VERSION}"
    const val retrofitConverterScalars= "com.squareup.retrofit2:converter-scalars:${Versions.RETROFIT_VERSION}"
    const val retrofitAdapterRxjava2 = "com.squareup.retrofit2:adapter-rxjava2:${Versions.RETROFIT_VERSION}"
    const val retrofitConverterGson = "com.squareup.retrofit2:converter-gson:${Versions.RETROFIT_VERSION}"
    const val autodispose= "com.uber.autodispose:autodispose-android-archcomponents:${Versions.AUTODISPOSE_VERSION}"
    const val loggingInterceptor = "com.squareup.okhttp3:logging-interceptor:${Versions.OKHTTP_VERSION}"
    const val zxingCore = "com.google.zxing:core:${Versions.ZXING_CORE_VERSION}"
    //    val zxingAndroidCore = "com.google.zxing:android-core:${Versions.ZXING_ANDROID_CORE_VERSION}"
    const val ormliteCore = "com.j256.ormlite:ormlite-core:${Versions.ORMLITE_VERSION}"
    const val ormLiteAndroid = "com.j256.ormlite:ormlite-android:${Versions.ORMLITE_VERSION}"
    const val baseQuickAdapter = "com.github.CymChad:BaseRecyclerViewAdapterHelper:${Versions.BASEQUICKADAPTER_VERSION}"
    const val glide = "com.github.bumptech.glide:glide:${Versions.GLIDE_VERSION}"
    const val glideCompiler = "com.github.bumptech.glide:compiler:${Versions.GLIDE_VERSION}"
    const val glideIntegration="com.github.bumptech.glide:okhttp3-integration:${Versions.GLIDE_VERSION}"
    const val swipeDelMenuLayout = "com.github.mcxtzhang:SwipeDelMenuLayout:${Versions.SWIPEDELMENULAYOUT_VERSION}"
    const val photoView = "com.github.chrisbanes:PhotoView:${Versions.PHOTOVIEW_VERSION}"
    const val appcenterAnalytics = "com.microsoft.appcenter:appcenter-analytics:${Versions.APPCENTER_VERSION}"
    const val appcenterCrashes = "com.microsoft.appcenter:appcenter-crashes:${Versions.APPCENTER_VERSION}"
    const val barcodescanner = "me.dm7.barcodescanner:zxing:${Versions.ZXING_BARCODE_SCANNER_VERSION}"
    const val jsoup = "org.jsoup:jsoup:${Versions.JSOUP_VERSION}"
    const val yanzhenjieRecyclerview = "com.yanzhenjie.recyclerview:x:${Versions.YANZHENJIE_RECYCLERVIEW_VERSION}"
    const val smartRefreshLayout = "com.scwang.smartrefresh:SmartRefreshLayout:${Versions.SMARTREFRESHLAYOUT_VERSION}"
    const val smartRefreshHeader = "com.scwang.smartrefresh:SmartRefreshHeader:${Versions.SMARTREFRESHLAYOUT_VERSION}"
    const val gifDrawable = "pl.droidsonroids.gif:android-gif-drawable:${Versions.GIF_DRAWABLE_VERSION}"
    const val luban = "top.zibin:Luban:${Versions.LUBAN_VERSION}"
    const val shortcutBadger = "me.leolin:ShortcutBadger:${Versions.SHORTCUTBADGER_VERSION}"
    const val androidsvg = "com.caverock:androidsvg:${Versions.ANDROIDSVG_VERSION}"
    const val stickyheaders = "com.timehop.stickyheadersrecyclerview:library:${Versions.STICKYHEADERS_VERSION}"
    const val animatedWebp = "com.facebook.fresco:animated-webp:${Versions.ANIMATED_WEBP_VERSION}"
    const val typeBuilder="com.github.ikidou:TypeBuilder:${Versions.TYPE_BUILDER_VERSION}"
    const val okhttp= "com.squareup.okhttp3:okhttp:${Versions.OKHTTP_VERSION}"
    const val bgaBanner="cn.bingoogolapple:bga-banner:${Versions.BGA_BANNER_VERSION}@aar"
    const val googlePhonenumber="com.googlecode.libphonenumber:libphonenumber:${Versions.GOOGLE_PHONENUMBER_VERSION}"
    const val eventBus = "org.greenrobot:eventbus:${Versions.EVENT_BUS_VERSION}"
    const val androidImageCropper = "com.theartofdev.edmodo:android-image-cropper:${Versions.ANDROID_IMAGE_CROPPER_VERSION}"
    const val gsyVideoPlayer="com.shuyu:GSYVideoPlayer:${Versions.GSY_VIDEOPLAYER_VERSION}"
    const val commonHelper="com.kongpf.commonhelper:common-helper:${Versions.COMMON_HELPER_VERSION}"
    const val roundCorners= "com.github.KuangGang:RoundCorners:${Versions.ROUND_CORNERS_VERSION}"

}

object AndroidX {
    const val appCompat = "androidx.appcompat:appcompat:${Versions.ANDROIDX_APP_COMPAT_VERSION}"
    const val legacyV4 = "androidx.legacy:legacy-support-v4:${Versions.ANDROIDX_LEGACY_V4_VERSION}"
    const val legacyV13 = "androidx.legacy:legacy-support-v13:${Versions.ANDROIDX_LEGACY_V13_VERSION}"
    const val multidex = "androidx.multidex:multidex:${Versions.ANDROIDX_MULTIDEX_VERSION}"
    const val material = "com.google.android.material:material:${Versions.ANDROIDX_MATERIAL_VERSION}"
    const val recyclerview = "androidx.recyclerview:recyclerview:${Versions.ANDROIDX_RECYCLERVIEW_VERSION}"
    const val preference = "androidx.preference:preference:${Versions.ANDROIDX_PREFERENCE_VERSION}"
    const val cardview = "androidx.cardview:cardview:${Versions.ANDROIDX_CARDVIEW_VERSION}"
    const val gridlayout = "androidx.gridlayout:gridlayout:${Versions.ANDROIDX_GRIDLAYOUT_VERSION}"
    const val annotationX = "androidx.annotation:annotation:${Versions.ANDROIDX_ANNOTATION_VERSION}"
    const val constraintlayout = "androidx.constraintlayout:constraintlayout:${Versions.ANDROIDX_CONSTRAINTLAYOUT_VERSION}"
    const val paging = "androidx.paging:paging-runtime:${Versions.ANDROIDX_PAGING_VERSION}"
    const val work = "androidx.work:work-runtime:${Versions.ANDROIDX_WORK_RUNTIME_VERSION}"
    const val core="androidx.core:core:${Versions.ANDROIDX_CORE_VERSION}"
    const val coreKtx="androidx.core:core-ktx:${Versions.ANDROIDX_CORE_KTX_VERSION}"
    const val room="androidx.room:room-runtime:${Versions.ANDROIDX_ROOM_VERSION}"
    const val roomKtx="androidx.room:room-ktx:${Versions.ANDROIDX_ROOM_VERSION}"
    const val roomTestHelper="androidx.room:room-testing:${Versions.ANDROIDX_ROOM_VERSION}"
    const val roomCompiler="androidx.room:room-compiler:${Versions.ANDROIDX_ROOM_VERSION}"
    const val roomRxJava2= "androidx.room:room-rxjava2:${Versions.ANDROIDX_ROOM_VERSION}"
    const val coordinatorlayout="androidx.coordinatorlayout:coordinatorlayout:${Versions.ANDROIDX_COORDINATORLAYOUT_VERSION}"
    const val databindingCommon="androidx.databinding:databinding-common:${Versions.ANDROIDX_DATABINDING_VERSION}"
    const val databindingAdapters="androidx.databinding:databinding-adapters:${Versions.ANDROIDX_DATABINDING_VERSION}"
    const val databindingRuntime="androidx.databinding:databinding-runtime:${Versions.ANDROIDX_DATABINDING_VERSION}"
    const val activity="androidx.activity:activity:${Versions.ANDROIDX_ACTIVITY_VERSION}"
    const val activityKtx="androidx.activity:activity-ktx:${Versions.ANDROIDX_ACTIVITY_VERSION}"
    const val fragment="androidx.fragment:fragment:${Versions.ANDROIDX_FRAGMENT_VERSION}"
    const val fragmentKtx="androidx.fragment:fragment-ktx:${Versions.ANDROIDX_FRAGMENT_VERSION}"
    const val lifecycleViewmodelKtx="androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.ANDROIDX_LIFECYCLE_VERSION}"
    const val lifecycleLivedataKtx="androidx.lifecycle:lifecycle-livedata-ktx:${Versions.ANDROIDX_LIFECYCLE_VERSION}"
    const val lifecycleRuntimeKtx="androidx.lifecycle:lifecycle-runtime-ktx:${Versions.ANDROIDX_LIFECYCLE_VERSION}"
    const val lifecycleViewmodelSavedstate="androidx.lifecycle:lifecycle-viewmodel-savedstate:${Versions.ANDROIDX_LIFECYCLE_VERSION}"
    const val lifecycleCompiler="androidx.lifecycle:lifecycle-compiler:${Versions.ANDROIDX_LIFECYCLE_VERSION}"
    const val lifecycleCommonJava8 = "androidx.lifecycle:lifecycle-common-java8:${Versions.ANDROIDX_LIFECYCLE_VERSION}"
    const val lifecycleService = "androidx.lifecycle:lifecycle-service:${Versions.ANDROIDX_LIFECYCLE_VERSION}"
    const val lifecycleProcess = "androidx.lifecycle:lifecycle-process:${Versions.ANDROIDX_LIFECYCLE_VERSION}"
    const val lifecycleReactivestreamsKtx= "androidx.lifecycle:lifecycle-reactivestreams-ktx:${Versions.ANDROIDX_LIFECYCLE_VERSION}"
    const val arcCoreTesting="androidx.arch.core:core-testing:${Versions.ANDROIDX_LIFECYCLE_ARCH_VERSION}"

}



